### ISSUE TITLE
Kertish-DFS on swarm

### ISSUE THREAD

**Issue by garanews** [freakmaxi/kertish-dfs#1]
There is any docker-compose.yml example for deploy on swarm?

**Comment by freakmaxi** [comment]
Hello,

Actually, you can use the docker-compose.yml in master. However, you may need to chop out some of the parts and customize the settings according to yourself.

Take a look at this
https://github.com/freakmaxi/kertish-dfs/blob/master/docker-compose.yml

In addition to that, I strongly advise that, do not use Data-Nodes in swarm setup. You may face data loss.
